services:
  - type: web
    name: restaren-laravel
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    rootDir: .
    plan: free
    autoDeploy: true
